version: '3.8'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  flask01:
    image: app:0.3
    environment:
      - APP_NAME=Flask01
    expose:
      - 5000

  flask02:
    image: app:0.3
    environment:
        - APP_NAME=Flask02
    expose:
      - 5000

  flask03:
    image: app:0.3
    environment:
        - APP_NAME=Flask03
    expose:
      - 5000

  balanceador:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    expose:
      - 6379
